/*
 * Author: doe300
 *
 * See the file "LICENSE" for the full license governing this code.
 */

#include "DRM.h"

#include <iostream>
#include <system_error>
#include <cstring>
#include <cinttypes>
#include <cstdio>

#ifndef MOCK_HAL
#include <fcntl.h>
#include <sys/ioctl.h>
#include <sys/mman.h>
#include <unistd.h>
#include <xf86drm.h>
#include <libdrm/vc4_drm.h>
#endif

using namespace vc4cl;

DRM::DRM() : fd(-1)
{
#ifndef MOCK_HAL
    fd = open("/dev/dri/card0", O_RDWR | O_CLOEXEC);
    if(fd < 0)
    {
        throw std::system_error(errno, std::system_category(), "Failed to open DRM device /dev/dri/card0");
    }
    DEBUG_LOG(DebugLevel::SYSCALL, std::cout << "[VC4CL] DRM device opened, fd: " << fd << std::endl)
#endif
}

DRM::~DRM()
{
#ifndef MOCK_HAL
    if(fd >= 0)
    {
        close(fd);
        DEBUG_LOG(DebugLevel::SYSCALL, std::cout << "[VC4CL] DRM device closed" << std::endl)
    }
#endif
}

std::unique_ptr<DeviceBuffer> DRM::allocateBuffer(
    const std::shared_ptr<SystemAccess>& system, unsigned sizeInBytes, CacheType cacheType)
{
#ifndef MOCK_HAL
    struct drm_vc4_create_bo create = {};
    create.size = sizeInBytes;

    if(ioctl(fd, DRM_IOCTL_VC4_CREATE_BO, &create) != 0)
    {
        DEBUG_LOG(DebugLevel::SYSCALL, std::cout << "[VC4CL] Failed to allocate DRM BO of size " << sizeInBytes << std::endl)
        return nullptr;
    }

    struct drm_vc4_mmap_bo mmap_bo = {};
    mmap_bo.handle = create.handle;

    if(ioctl(fd, DRM_IOCTL_VC4_MMAP_BO, &mmap_bo) != 0)
    {
        DEBUG_LOG(DebugLevel::SYSCALL, std::cout << "[VC4CL] Failed to mmap DRM BO handle: " << create.handle << std::endl)
        // Ideally we should free the BO here, but DRM handles that when closed/freed. 
        // Need to explicitly close GEM handle?
        struct drm_gem_close gem_close = {};
        gem_close.handle = create.handle;
        ioctl(fd, DRM_IOCTL_GEM_CLOSE, &gem_close);
        return nullptr;
    }

    void* hostPointer = mmap(nullptr, sizeInBytes, PROT_READ | PROT_WRITE, MAP_SHARED, fd, mmap_bo.offset);
    if(hostPointer == MAP_FAILED)
    {
        DEBUG_LOG(DebugLevel::SYSCALL, std::cout << "[VC4CL] mmap failed for DRM BO handle: " << create.handle << std::endl)
        struct drm_gem_close gem_close = {};
        gem_close.handle = create.handle;
        ioctl(fd, DRM_IOCTL_GEM_CLOSE, &gem_close);
        return nullptr;
    }

    // VC4 DRM doesn't explicitly expose the QPU bus address because the kernel driver relocates BOs on submit.
    // However, for compatibility with the current HAL buffer object, we store the handle as the "qpuPointer".
    DevicePointer qpuPointer(create.handle);

    DEBUG_LOG(DebugLevel::MEMORY,
        std::cout << "Allocated " << sizeInBytes << " bytes of DRM buffer: handle " << create.handle 
                  << ", host address " << hostPointer << std::endl)
                  
    return std::unique_ptr<DeviceBuffer>{new DeviceBuffer(system, create.handle, qpuPointer, hostPointer, sizeInBytes)};
#else
    return nullptr;
#endif
}

bool DRM::deallocateBuffer(const DeviceBuffer* buffer)
{
#ifndef MOCK_HAL
    if(buffer->hostPointer != nullptr)
    {
        munmap(buffer->hostPointer, buffer->size);
    }
    
    struct drm_gem_close gem_close = {};
    gem_close.handle = buffer->memHandle;
    
    if(ioctl(fd, DRM_IOCTL_GEM_CLOSE, &gem_close) != 0)
    {
        return false;
    }
    
    DEBUG_LOG(DebugLevel::MEMORY,
        std::cout << "Deallocated " << buffer->size << " bytes of DRM buffer: handle " << buffer->memHandle << std::endl)
    return true;
#else
    return true;
#endif
}

ExecutionHandle DRM::executeQPU(unsigned numQPUs, std::pair<uint32_t*, unsigned> controlAddress, bool flushBuffer,
    std::chrono::milliseconds timeout, const std::vector<uint32_t>& boHandles)
{
#ifndef MOCK_HAL
    if (boHandles.empty())
        return ExecutionHandle{false};

    // The unified buffer handle is the first in the list
    uint32_t main_handle = boHandles[0];

    // Extract offsets from the launch message generated by AS_GPU_ADDRESS (which adds handle to offset)
    uint32_t uniforms_offset = controlAddress.first[0] - main_handle;
    uint32_t code_offset = controlAddress.first[1] - main_handle;

    // Build Shader Record (36 bytes for 0 attributes, prepended with 3 BO handles)
    std::vector<uint8_t> shader_rec;
    uint32_t bo_indices[] = {0, 0, 0}; // FS, VS, CS all point to the main BO (index 0 in bo_handles)
    shader_rec.insert(shader_rec.end(), reinterpret_cast<uint8_t*>(bo_indices), reinterpret_cast<uint8_t*>(bo_indices) + sizeof(bo_indices));

    uint8_t rec[36] = {};
    // CS code offset (offset +28)
    *reinterpret_cast<uint32_t*>(&rec[28]) = code_offset;
    // CS uniforms offset (offset +32)
    *reinterpret_cast<uint32_t*>(&rec[32]) = uniforms_offset;
    
    // Disable threading for coordinate shader
    *reinterpret_cast<uint16_t*>(&rec[24]) = 0; 
    
    shader_rec.insert(shader_rec.end(), rec, rec + sizeof(rec));

    // Pad to 16-byte alignment
    while (shader_rec.size() % 16 != 0) {
        shader_rec.push_back(0);
    }

    // Build Binner Command List
    std::vector<uint8_t> bin_cl;
    bin_cl.push_back(64); // VC4_PACKET_GL_SHADER_STATE
    
    // Pointer to the shader record within our shader_rec buffer (offset after the BO indices)
    uint32_t rec_offset = sizeof(bo_indices);
    // Number of attributes encoded in lowest 3 bits. 1 attribute (dummy) to avoid 0 which means 8.
    uint32_t addr = rec_offset | 1;
    bin_cl.insert(bin_cl.end(), reinterpret_cast<uint8_t*>(&addr), reinterpret_cast<uint8_t*>(&addr) + 4);
    
    bin_cl.push_back(0); // VC4_PACKET_HALT

    // Submit CL
    struct drm_vc4_submit_cl submit = {};
    submit.bo_handles = reinterpret_cast<uint64_t>(boHandles.data());
    submit.bo_handle_count = static_cast<uint32_t>(boHandles.size());
    
    submit.bin_cl = reinterpret_cast<uint64_t>(bin_cl.data());
    submit.bin_cl_size = static_cast<uint32_t>(bin_cl.size());
    
    submit.shader_rec = reinterpret_cast<uint64_t>(shader_rec.data());
    submit.shader_rec_size = static_cast<uint32_t>(shader_rec.size());
    submit.shader_rec_count = 1;

    // For pure compute without texture/TMU access via uniform stream, uniforms buffer can be empty
    submit.uniforms = 0;
    submit.uniforms_size = 0;

    DEBUG_LOG(DebugLevel::SYSCALL, std::cout << "[VC4CL] Submitting DRM_IOCTL_VC4_SUBMIT_CL for compute job" << std::endl)
    
    if(ioctl(fd, DRM_IOCTL_VC4_SUBMIT_CL, &submit) != 0)
    {
        DEBUG_LOG(DebugLevel::SYSCALL, std::cout << "[VC4CL] DRM_IOCTL_VC4_SUBMIT_CL failed: " << strerror(errno) << std::endl)
        return ExecutionHandle{false};
    }

    // Wait for completion (using DRM_IOCTL_VC4_WAIT_SEQNO)
    struct drm_vc4_wait_seqno wait = {};
    wait.seqno = submit.seqno;
    wait.timeout_ns = timeout.count() * 1000000ull; // ms to ns

    if(ioctl(fd, DRM_IOCTL_VC4_WAIT_SEQNO, &wait) != 0)
    {
        DEBUG_LOG(DebugLevel::SYSCALL, std::cout << "[VC4CL] DRM_IOCTL_VC4_WAIT_SEQNO failed: " << strerror(errno) << std::endl)
        return ExecutionHandle{false};
    }

    return ExecutionHandle{true};
#else
    return ExecutionHandle{false};
#endif
}

// Helper: read a uint64_t from a sysfs node
static bool read_sysfs_u64(const char* path, uint64_t& out) noexcept
{
    FILE* f = fopen(path, "r");
    if(!f) return false;
    bool ok = (fscanf(f, "%" SCNu64, &out) == 1);
    fclose(f);
    return ok;
}

bool DRM::readValue(SystemQuery query, uint32_t& output) noexcept
{
#ifndef MOCK_HAL
    switch(query)
    {
    case SystemQuery::NUM_QPUS:
    {
        // V3D_IDENT0 encodes QPU count in bits [23:20]
        struct drm_vc4_get_param param = {};
        param.param = 0; // DRM_VC4_PARAM_V3D_IDENT0
        if(ioctl(fd, DRM_IOCTL_VC4_GET_PARAM, &param) == 0)
        {
            // QPUs per slice in bits [23:20], slices in bits [27:24]
            uint32_t ident0 = static_cast<uint32_t>(param.value);
            uint32_t qpus_per_slice = (ident0 >> 20) & 0xF;
            uint32_t slices = (ident0 >> 24) & 0xF;
            output = qpus_per_slice * slices;
            if(output == 0) output = 12; // safe fallback for RPi 1/2/3 (12 QPUs)
            return true;
        }
        return false;
    }
    case SystemQuery::TOTAL_GPU_MEMORY_IN_BYTES:
    {
        // Read CMA pool size from sysfs (Raspberry Pi)
        // /sys/kernel/debug/dma_pools is not always readable; try /proc/meminfo cma fields
        uint64_t val = 0;
        const char* cma_path = "/sys/module/cma/parameters/size";
        if(read_sysfs_u64(cma_path, val) && val > 0)
        {
            output = static_cast<uint32_t>(val);
            return true;
        }
        // Try reading from cmdline as fallback
        // If nothing works, return false -> use default 256MB from hal.h
        return false;
    }
    case SystemQuery::CURRENT_QPU_CLOCK_RATE_IN_HZ:
    {
        // Read from raspberrypi firmware sysfs
        uint64_t val = 0;
        if(read_sysfs_u64("/sys/devices/system/cpu/cpufreq/policy0/scaling_cur_freq", val))
        {
            // That's CPU freq; try VC4-specific paths
        }
        // Try vcgencmd-style sysfs or vc4 V3D debug: no standard path.
        // Fall back to max clock.
        return false;
    }
    case SystemQuery::MAXIMUM_QPU_CLOCK_RATE_IN_HZ:
    {
        // Try /sys/kernel/debug/clk/<vc4-v3d clock>/clk_rate (requires debugfs)
        uint64_t val = 0;
        const char* paths[] = {
            "/sys/kernel/debug/clk/v3d/clk_rate",
            "/sys/kernel/debug/clk/vc4-v3d/clk_rate",
            nullptr
        };
        for(int i = 0; paths[i]; ++i)
        {
            if(read_sysfs_u64(paths[i], val) && val > 0)
            {
                output = static_cast<uint32_t>(val);
                return true;
            }
        }
        // Raspberry Pi 3 V3D runs at 300MHz; RPi 1/2 at 250MHz. Use 250MHz as safe default.
        output = 250000000u;
        return true;
    }
    case SystemQuery::QPU_TEMPERATURE_IN_MILLI_DEGREES:
    {
        // /sys/class/thermal/thermal_zone0/temp (millidegrees on RPi)
        uint64_t val = 0;
        if(read_sysfs_u64("/sys/class/thermal/thermal_zone0/temp", val))
        {
            output = static_cast<uint32_t>(val);
            return true;
        }
        return false;
    }
    case SystemQuery::TOTAL_VPM_MEMORY_IN_BYTES:
        // VPM is 12KB on VC4
        output = 12 * 1024;
        return true;
    default:
        return false;
    }
#else
    return false;
#endif
}
